=begin
#Fly Machines API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FlySDK::ApiStopConfig
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FlySDK::ApiStopConfig do
  let(:instance) { FlySDK::ApiStopConfig.new }

  describe 'test an instance of ApiStopConfig' do
    it 'should create an instance of ApiStopConfig' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(FlySDK::ApiStopConfig)
    end
  end

  describe 'test attribute "signal"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "timeout"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
