=begin
#Fly Machines API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FlyApi::ApiMachineMetrics
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FlyApi::ApiMachineMetrics do
  let(:instance) { FlyApi::ApiMachineMetrics.new }

  describe 'test an instance of ApiMachineMetrics' do
    it 'should create an instance of ApiMachineMetrics' do
      expect(instance).to be_instance_of(FlyApi::ApiMachineMetrics)
    end
  end
  describe 'test attribute "path"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "port"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
