# coding: utf-8

"""
    Fly Machines API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fly-sdk.models.api_http_options import ApiHTTPOptions  # noqa: E501

class TestApiHTTPOptions(unittest.TestCase):
    """ApiHTTPOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiHTTPOptions:
        """Test ApiHTTPOptions
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiHTTPOptions`
        """
        model = ApiHTTPOptions()  # noqa: E501
        if include_optional:
            return ApiHTTPOptions(
                compress = True,
                h2_backend = True,
                response = fly-sdk.models.api/http_response_options.api.HTTPResponseOptions(
                    headers = {
                        'key' : None
                        }, )
            )
        else:
            return ApiHTTPOptions(
        )
        """

    def testApiHTTPOptions(self):
        """Test ApiHTTPOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
