# coding: utf-8

"""
    Fly Machines API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from fly-sdk.models.main_status_code import MainStatusCode  # noqa: E501

class TestMainStatusCode(unittest.TestCase):
    """MainStatusCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMainStatusCode(self):
        """Test MainStatusCode"""
        # inst = MainStatusCode()

if __name__ == '__main__':
    unittest.main()
