# coding: utf-8

"""
    Fly Machines API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fly-sdk.api.volumes_api import VolumesApi  # noqa: E501


class TestVolumesApi(unittest.TestCase):
    """VolumesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VolumesApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_volume_delete(self) -> None:
        """Test case for volume_delete

        """
        pass

    def test_volumes_create(self) -> None:
        """Test case for volumes_create

        """
        pass

    def test_volumes_extend(self) -> None:
        """Test case for volumes_extend

        """
        pass

    def test_volumes_get_by_id(self) -> None:
        """Test case for volumes_get_by_id

        """
        pass

    def test_volumes_get_snapshots(self) -> None:
        """Test case for volumes_get_snapshots

        """
        pass

    def test_volumes_list(self) -> None:
        """Test case for volumes_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
