# coding: utf-8

"""
    Fly Machines API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fly-sdk.api.apps_api import AppsApi


class TestAppsApi(unittest.TestCase):
    """AppsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppsApi()

    def tearDown(self) -> None:
        pass

    def test_apps_create(self) -> None:
        """Test case for apps_create

        """
        pass

    def test_apps_delete(self) -> None:
        """Test case for apps_delete

        """
        pass

    def test_apps_list(self) -> None:
        """Test case for apps_list

        """
        pass

    def test_apps_show(self) -> None:
        """Test case for apps_show

        """
        pass


if __name__ == '__main__':
    unittest.main()
