# coding: utf-8

"""
    Fly Machines API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictInt, StrictStr, validator
from pydantic import Field

class ApiMachineRestart(BaseModel):
    """
    The Machine restart policy defines whether and how flyd restarts a Machine after its main process exits. See https://fly.io/docs/machines/guides-examples/machine-restart-policy/.  # noqa: E501
    """
    max_retries: Optional[StrictInt] = Field(default=None, description="When policy is on-failure, the maximum number of times to attempt to restart the Machine before letting it stop.")
    policy: Optional[StrictStr] = Field(default=None, description="* no - Never try to restart a Machine automatically when its main process exits, whether that’s on purpose or on a crash. * always - Always restart a Machine automatically and never let it enter a stopped state, even when the main process exits cleanly. * on-failure - Try up to MaxRetries times to automatically restart the Machine if it exits with a non-zero exit code. Default when no explicit policy is set, and for Machines with schedules.")
    __properties = ["max_retries", "policy"]

    @validator('policy')
    def policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('no', 'always', 'on-failure'):
            raise ValueError("must be one of enum values ('no', 'always', 'on-failure')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ApiMachineRestart:
        """Create an instance of ApiMachineRestart from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ApiMachineRestart:
        """Create an instance of ApiMachineRestart from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ApiMachineRestart.parse_obj(obj)

        _obj = ApiMachineRestart.parse_obj({
            "max_retries": obj.get("max_retries"),
            "policy": obj.get("policy")
        })
        return _obj


