=begin
#Fly Machines API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for FlyApi::VolumesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VolumesApi' do
  before do
    # run before each test
    @api_instance = FlyApi::VolumesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VolumesApi' do
    it 'should create an instance of VolumesApi' do
      expect(@api_instance).to be_instance_of(FlyApi::VolumesApi)
    end
  end

  # unit tests for volume_delete
  # @param app_name Fly App Name
  # @param volume_id Volume ID
  # @param [Hash] opts the optional parameters
  # @return [Volume]
  describe 'volume_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for volumes_create
  # @param app_name Fly App Name
  # @param request Request body
  # @param [Hash] opts the optional parameters
  # @return [Volume]
  describe 'volumes_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for volumes_extend
  # @param app_name Fly App Name
  # @param volume_id Volume ID
  # @param request Request body
  # @param [Hash] opts the optional parameters
  # @return [ExtendVolumeResponse]
  describe 'volumes_extend test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for volumes_get_by_id
  # @param app_name Fly App Name
  # @param volume_id Volume ID
  # @param [Hash] opts the optional parameters
  # @return [Volume]
  describe 'volumes_get_by_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for volumes_get_snapshots
  # @param app_name Fly App Name
  # @param volume_id Volume ID
  # @param [Hash] opts the optional parameters
  # @return [Array<VolumeSnapshot>]
  describe 'volumes_get_snapshots test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for volumes_list
  # @param app_name Fly App Name
  # @param [Hash] opts the optional parameters
  # @return [Array<Volume>]
  describe 'volumes_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
