/*
Fly Machines API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fly-sdk

import (
	"encoding/json"
)

// checks if the ListApp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListApp{}

// ListApp struct for ListApp
type ListApp struct {
	MachineCount *int32 `json:"machine_count,omitempty"`
	Name *string `json:"name,omitempty"`
	Network map[string]interface{} `json:"network,omitempty"`
}

// NewListApp instantiates a new ListApp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListApp() *ListApp {
	this := ListApp{}
	return &this
}

// NewListAppWithDefaults instantiates a new ListApp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAppWithDefaults() *ListApp {
	this := ListApp{}
	return &this
}

// GetMachineCount returns the MachineCount field value if set, zero value otherwise.
func (o *ListApp) GetMachineCount() int32 {
	if o == nil || IsNil(o.MachineCount) {
		var ret int32
		return ret
	}
	return *o.MachineCount
}

// GetMachineCountOk returns a tuple with the MachineCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListApp) GetMachineCountOk() (*int32, bool) {
	if o == nil || IsNil(o.MachineCount) {
		return nil, false
	}
	return o.MachineCount, true
}

// HasMachineCount returns a boolean if a field has been set.
func (o *ListApp) HasMachineCount() bool {
	if o != nil && !IsNil(o.MachineCount) {
		return true
	}

	return false
}

// SetMachineCount gets a reference to the given int32 and assigns it to the MachineCount field.
func (o *ListApp) SetMachineCount(v int32) {
	o.MachineCount = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ListApp) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListApp) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ListApp) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ListApp) SetName(v string) {
	o.Name = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *ListApp) GetNetwork() map[string]interface{} {
	if o == nil || IsNil(o.Network) {
		var ret map[string]interface{}
		return ret
	}
	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListApp) GetNetworkOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Network) {
		return map[string]interface{}{}, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *ListApp) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given map[string]interface{} and assigns it to the Network field.
func (o *ListApp) SetNetwork(v map[string]interface{}) {
	o.Network = v
}

func (o ListApp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListApp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MachineCount) {
		toSerialize["machine_count"] = o.MachineCount
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	return toSerialize, nil
}

type NullableListApp struct {
	value *ListApp
	isSet bool
}

func (v NullableListApp) Get() *ListApp {
	return v.value
}

func (v *NullableListApp) Set(val *ListApp) {
	v.value = val
	v.isSet = true
}

func (v NullableListApp) IsSet() bool {
	return v.isSet
}

func (v *NullableListApp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListApp(val *ListApp) *NullableListApp {
	return &NullableListApp{value: val, isSet: true}
}

func (v NullableListApp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListApp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


