=begin
#Fly Machines API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.1.0-SNAPSHOT

=end

require 'date'
require 'time'

module FlySDK
  class ApiMachineConfig
    # Optional boolean telling the Machine to destroy itself once it’s complete (default false)
    attr_accessor :auto_destroy

    attr_accessor :checks

    # Deprecated: use Service.Autostart instead
    attr_accessor :disable_machine_autostart

    attr_accessor :dns

    # An object filled with key/value pairs to be set as environment variables
    attr_accessor :env

    attr_accessor :files

    attr_accessor :guest

    # The docker image to run
    attr_accessor :image

    attr_accessor :init

    attr_accessor :metadata

    attr_accessor :metrics

    attr_accessor :mounts

    attr_accessor :processes

    attr_accessor :restart

    attr_accessor :schedule

    attr_accessor :services

    # Deprecated: use Guest instead
    attr_accessor :size

    # Standbys enable a machine to be a standby for another. In the event of a hardware failure, the standby machine will be started.
    attr_accessor :standbys

    attr_accessor :statics

    attr_accessor :stop_config

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'auto_destroy' => :'auto_destroy',
        :'checks' => :'checks',
        :'disable_machine_autostart' => :'disable_machine_autostart',
        :'dns' => :'dns',
        :'env' => :'env',
        :'files' => :'files',
        :'guest' => :'guest',
        :'image' => :'image',
        :'init' => :'init',
        :'metadata' => :'metadata',
        :'metrics' => :'metrics',
        :'mounts' => :'mounts',
        :'processes' => :'processes',
        :'restart' => :'restart',
        :'schedule' => :'schedule',
        :'services' => :'services',
        :'size' => :'size',
        :'standbys' => :'standbys',
        :'statics' => :'statics',
        :'stop_config' => :'stop_config'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'auto_destroy' => :'Boolean',
        :'checks' => :'Hash<String, ApiMachineCheck>',
        :'disable_machine_autostart' => :'Boolean',
        :'dns' => :'ApiDNSConfig',
        :'env' => :'Hash<String, String>',
        :'files' => :'Array<ApiFile>',
        :'guest' => :'ApiMachineGuest',
        :'image' => :'String',
        :'init' => :'ApiMachineInit',
        :'metadata' => :'Hash<String, String>',
        :'metrics' => :'ApiMachineMetrics',
        :'mounts' => :'Array<ApiMachineMount>',
        :'processes' => :'Array<ApiMachineProcess>',
        :'restart' => :'ApiMachineRestart',
        :'schedule' => :'String',
        :'services' => :'Array<ApiMachineService>',
        :'size' => :'String',
        :'standbys' => :'Array<String>',
        :'statics' => :'Array<ApiStatic>',
        :'stop_config' => :'ApiStopConfig'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `FlySDK::ApiMachineConfig` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `FlySDK::ApiMachineConfig`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'auto_destroy')
        self.auto_destroy = attributes[:'auto_destroy']
      end

      if attributes.key?(:'checks')
        if (value = attributes[:'checks']).is_a?(Hash)
          self.checks = value
        end
      end

      if attributes.key?(:'disable_machine_autostart')
        self.disable_machine_autostart = attributes[:'disable_machine_autostart']
      end

      if attributes.key?(:'dns')
        self.dns = attributes[:'dns']
      end

      if attributes.key?(:'env')
        if (value = attributes[:'env']).is_a?(Hash)
          self.env = value
        end
      end

      if attributes.key?(:'files')
        if (value = attributes[:'files']).is_a?(Array)
          self.files = value
        end
      end

      if attributes.key?(:'guest')
        self.guest = attributes[:'guest']
      end

      if attributes.key?(:'image')
        self.image = attributes[:'image']
      end

      if attributes.key?(:'init')
        self.init = attributes[:'init']
      end

      if attributes.key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Hash)
          self.metadata = value
        end
      end

      if attributes.key?(:'metrics')
        self.metrics = attributes[:'metrics']
      end

      if attributes.key?(:'mounts')
        if (value = attributes[:'mounts']).is_a?(Array)
          self.mounts = value
        end
      end

      if attributes.key?(:'processes')
        if (value = attributes[:'processes']).is_a?(Array)
          self.processes = value
        end
      end

      if attributes.key?(:'restart')
        self.restart = attributes[:'restart']
      end

      if attributes.key?(:'schedule')
        self.schedule = attributes[:'schedule']
      end

      if attributes.key?(:'services')
        if (value = attributes[:'services']).is_a?(Array)
          self.services = value
        end
      end

      if attributes.key?(:'size')
        self.size = attributes[:'size']
      end

      if attributes.key?(:'standbys')
        if (value = attributes[:'standbys']).is_a?(Array)
          self.standbys = value
        end
      end

      if attributes.key?(:'statics')
        if (value = attributes[:'statics']).is_a?(Array)
          self.statics = value
        end
      end

      if attributes.key?(:'stop_config')
        self.stop_config = attributes[:'stop_config']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          auto_destroy == o.auto_destroy &&
          checks == o.checks &&
          disable_machine_autostart == o.disable_machine_autostart &&
          dns == o.dns &&
          env == o.env &&
          files == o.files &&
          guest == o.guest &&
          image == o.image &&
          init == o.init &&
          metadata == o.metadata &&
          metrics == o.metrics &&
          mounts == o.mounts &&
          processes == o.processes &&
          restart == o.restart &&
          schedule == o.schedule &&
          services == o.services &&
          size == o.size &&
          standbys == o.standbys &&
          statics == o.statics &&
          stop_config == o.stop_config
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [auto_destroy, checks, disable_machine_autostart, dns, env, files, guest, image, init, metadata, metrics, mounts, processes, restart, schedule, services, size, standbys, statics, stop_config].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = FlySDK.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
